### ISSUE TITLE
Can't install completely and can't run examples on Mac OS X

### ISSUE THREAD

**Issue by studiotimo** [caspervonb/amok#139]
Hi @caspervonb,

Thanks for the great project. I really wish I could use amok, but I can't get it to work on my Mac OS X for some reason. I'm using Mac OS X v10.10.4 (Yosemite), and Chrome 44.0.2403.155. I've been pulling my hairs and only a few left...

Let me share what I see when I tried installing amok and when I tried to run react-simple example.

#### When I was installing amok:

```
glee@mm-mac-3282:~ $ sudo npm install -g amok
 
> fsevents@0.3.8 install /usr/local/lib/node_modules/amok/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node

> bufferutil@1.1.0 install /usr/local/lib/node_modules/amok/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node

> utf-8-validate@1.1.0 install /usr/local/lib/node_modules/amok/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
/usr/local/bin/amok -> /usr/local/lib/node_modules/amok/bin/amok
npm WARN unmet dependency /usr/local/lib/node_modules/bower/node_modules/inquirer requires chalk@'^0.5.0' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/bower/node_modules/chalk,
npm WARN unmet dependency which is version 1.1.1
npm WARN unmet dependency /usr/local/lib/node_modules/bower/node_modules/cardinal/node_modules/redeyed requires esprima@'~1.0.4' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/esprima,
npm WARN unmet dependency which is version 2.5.0
npm WARN unmet dependency /usr/local/lib/node_modules/bower/node_modules/configstore/node_modules/js-yaml requires esprima@'~2.2.0' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/esprima,
npm WARN unmet dependency which is version 2.5.0
npm WARN unmet dependency /usr/local/lib/node_modules/learnyounode/node_modules/workshopper/node_modules/msee requires xtend@'~2.1.1' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/learnyounode/node_modules/workshopper/node_modules/xtend,
npm WARN unmet dependency which is version 3.0.0
amok@1.1.2 /usr/local/lib/node_modules/amok
├── rdbg@1.1.0
├── mime@1.3.4
├── commander@2.8.1 (graceful-readlink@1.0.1)
├── temp@0.8.3 (os-tmpdir@1.0.1, rimraf@2.2.8)
├── ware@1.3.0 (wrap-fn@0.1.4)
├── browser_process@1.0.4 (which@1.1.1)
├── compiler_process@1.0.0 (which@1.1.1)
├── chokidar@1.0.5 (path-is-absolute@1.0.0, arrify@1.0.0, is-glob@1.1.3, glob-parent@1.2.0, async-each@0.1.6, is-binary-path@1.0.1, readdirp@1.4.0, anymatch@1.3.0, fsevents@0.3.8)
└── ws@0.7.2 (options@0.0.6, ultron@1.0.2, bufferutil@1.1.0, utf-8-validate@1.1.0)
```

#### When I tried to run react-simple example:

```
glee@mm-mac-3282:~/amok-examples/react-simple (master=) $ sudo npm start

> @ start /Users/glee/amok-examples/react-simple
> amok --hot --browser chrome --compiler browserify index.js -- --transform reactify --fast

events.js:85
      throw er; // Unhandled 'error' event
            ^
TypeError: Bad compiler command
    at Object.options (/usr/local/lib/node_modules/amok/node_modules/compiler_process/lib/index.js:55:11)
    at Ware.compiler (/usr/local/lib/node_modules/amok/lib/compiler.js:30:37)
    at Ware.<anonymous> (/usr/local/lib/node_modules/amok/node_modules/ware/node_modules/wrap-fn/index.js:45:19)
    at next (/usr/local/lib/node_modules/amok/node_modules/ware/lib/index.js:85:20)
    at /usr/local/lib/node_modules/amok/node_modules/ware/node_modules/wrap-fn/index.js:121:18
    at Server.ready (/usr/local/lib/node_modules/amok/lib/server.js:27:7)
    at Server.g (events.js:199:16)
    at Server.emit (events.js:104:17)
    at net.js:1171:12
    at process._tickDomainCallback (node.js:381:11)

npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.14.0
npm ERR! code ELIFECYCLE
npm ERR! @ start: `amok --hot --browser chrome --compiler browserify index.js -- --transform reactify --fast`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ start script 'amok --hot --browser chrome --compiler browserify index.js -- --transform reactify --fast'.
npm ERR! This is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     amok --hot --browser chrome --compiler browserify index.js -- --transform reactify --fast
npm ERR! You can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/glee/amok-examples/react-simple/npm-debug.log
```

* npm-debug.log for this:
```
glee@mm-mac-3282:~/amok-examples/react-simple (master=) $ cat /Users/glee/amok-examples/react-simple/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.14.0
3 info using node@v0.12.7
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart @
6 info start @
7 verbose unsafe-perm in lifecycle true
8 info @ Failed to exec start script
9 verbose stack Error: @ start: `amok --hot --browser chrome --compiler browserify index.js -- --transform reactify --fast`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
10 verbose pkgid @
11 verbose cwd /Users/glee/amok-examples/react-simple
12 error Darwin 14.4.0
13 error argv "node" "/usr/local/bin/npm" "start"
14 error node v0.12.7
15 error npm  v2.14.0
16 error code ELIFECYCLE
17 error @ start: `amok --hot --browser chrome --compiler browserify index.js -- --transform reactify --fast`
17 error Exit status 1
18 error Failed at the @ start script 'amok --hot --browser chrome --compiler browserify index.js -- --transform reactify --fast'.
18 error This is most likely a problem with the  package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     amok --hot --browser chrome --compiler browserify index.js -- --transform reactify --fast
18 error You can get their info via:
18 error     npm owner ls
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

Am I missing something, and am I the only one who experiences this in Mac?

My node version is 0.12.7 and npm version is 2.14.0. Please let me know if I need to provide more information.

Thank you!

**Comment by caspervonb** [comment]
Example is slightly out of date, some time ago pre 1.0, I opted for using the binary name, which in this case is watchify.

```sh
$  amok --hot --browser chrome --compiler watchify index.js -- --transform reactify --fast
```

**Comment by studiotimo** [comment]
Thanks for your reply. So, this is what I did. (Installed watchify and then tried to run react-simple example)

```
glee@mm-mac-3282:~/amok-examples/react-simple (master=) $ sudo npm install -g watchify
Password: 
 
> fsevents@0.3.8 install /usr/local/lib/node_modules/watchify/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
/usr/local/bin/watchify -> /usr/local/lib/node_modules/watchify/bin/cmd.js
npm WARN unmet dependency /usr/local/lib/node_modules/bower/node_modules/inquirer requires chalk@'^0.5.0' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/bower/node_modules/chalk,
npm WARN unmet dependency which is version 1.1.1
npm WARN unmet dependency /usr/local/lib/node_modules/bower/node_modules/cardinal/node_modules/redeyed requires esprima@'~1.0.4' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/esprima,
npm WARN unmet dependency which is version 2.5.0
npm WARN unmet dependency /usr/local/lib/node_modules/bower/node_modules/configstore/node_modules/js-yaml requires esprima@'~2.2.0' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/esprima,
npm WARN unmet dependency which is version 2.5.0
npm WARN unmet dependency /usr/local/lib/node_modules/learnyounode/node_modules/workshopper/node_modules/msee requires xtend@'~2.1.1' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/learnyounode/node_modules/workshopper/node_modules/xtend,
npm WARN unmet dependency which is version 3.0.0
watchify@3.3.1 /usr/local/lib/node_modules/watchify
├── defined@1.0.0
├── xtend@4.0.0
├── outpipe@1.1.1 (shell-quote@1.4.3)
├── through2@0.6.5 (readable-stream@1.0.33)
├── chokidar@1.0.5 (arrify@1.0.0, path-is-absolute@1.0.0, is-glob@1.1.3, glob-parent@1.2.0, async-each@0.1.6, is-binary-path@1.0.1, fsevents@0.3.8, readdirp@1.4.0)
├── anymatch@1.3.0 (arrify@1.0.0, micromatch@2.2.0)
└── browserify@11.0.1 (https-browserify@0.0.0, tty-browserify@0.0.0, builtins@0.0.7, constants-browserify@0.0.1, path-browserify@0.0.0, htmlescape@1.1.0, os-browserify@0.1.2, isarray@0.0.1, inherits@2.0.1, browser-resolve@1.9.1, commondir@0.0.1, string_decoder@0.10.31, process@0.11.1, shell-quote@0.0.1, punycode@1.3.2, domain-browser@1.1.4, stream-browserify@2.0.0, assert@1.3.0, querystring-es3@0.2.1, timers-browserify@1.4.1, deps-sort@1.3.9, util@0.10.3, events@1.0.2, through2@1.1.1, resolve@1.1.6, has@1.0.1, parents@1.0.1, vm-browserify@0.0.4, console-browserify@1.1.0, subarg@1.0.0, url@0.10.3, shasum@1.0.1, concat-stream@1.4.10, readable-stream@2.0.2, buffer@3.4.3, JSONStream@1.0.4, stream-http@1.5.0, duplexer2@0.0.2, read-only-stream@1.1.1, labeled-stream-splicer@1.0.2, syntax-error@1.1.4, browserify-zlib@0.1.4, glob@4.5.3, insert-module-globals@6.5.2, browser-pack@5.0.1, crypto-browserify@3.9.14, module-deps@3.9.0)
```

and then, by using the command you suggested, Chrome browser was launched with http://localhost:9966/ in the URL. (I see 3 errors in Terminal, btw. Are these okay?)
```
glee@mm-mac-3282:~/amok-examples/react-simple (master=) $ amok --hot --browser chrome --compiler watchify index.js -- --transform reactify --fast
[18405:55059:0823/182455:ERROR:socket_libevent.cc(122)] bind() returned an error, errno=48: Address already in use
[18405:55059:0823/182455:ERROR:devtools_http_handler.cc(224)] Cannot start http server for devtools. Stop devtools.
[18405:1299:0823/182456:ERROR:bluetooth_adapter_mac.mm(100)] Not implemented reached in virtual bool device::BluetoothAdapterMac::IsDiscoverable() const
```

Also, to be able to test the 'patch' functionality, before I launched it using the above command, I had added this block of code at the end of react-simple/index.js but "patch" event doesn't fire when I edit a part of index.js and save.
```
window.addEventListener("patch", function () {
	console.log('patch');
	React.render(
		<ExampleApplication elapsed={new Date().getTime() - start} />,
    	document.body
	);
});
```

Do you have any idea for me to get this through? Also, Do you think what I saw as Errors and Warnings are fine? Thanks.

**Comment by caspervonb** [comment]
Something is already listening on port '9222' and chrome can't start its debug server. Effectively stalling everything, amok never actually starts.

Try killing it, you can figure out the pid of what is listening on 9222 with
```sh
$ lsof -i tcp:9222
```

**Comment by studiotimo** [comment]
That was it. Works great now. Thank you so much for your quick replies, @caspervonb!
(Please let me close this as your comments solved my issue.)
