### ISSUE TITLE
npm install -g amok fails (on OS X? on Node 4.1?)

### ISSUE THREAD

**Issue by omnidan** [caspervonb/amok#158]
When trying to do `npm install -g amok`:

```
dan@galaxy ~> npm -v
3.3.3
dan@galaxy ~> node -v
v4.1.0
dan@galaxy ~> npm install -g amok
/usr/local/bin/amok -> /usr/local/lib/node_modules/amok/bin/amok

> bufferutil@1.1.0 install /usr/local/lib/node_modules/amok/node_modules/bufferutil
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
In file included from ../src/bufferutil.cc:16:
../node_modules/nan/nan.h:261:25: error: redefinition of '_NanEnsureLocal'
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../node_modules/nan/nan.h:256:25: note: previous definition is here
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                        ^
../node_modules/nan/nan.h:661:13: error: no member named 'smalloc' in namespace 'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~^
../node_modules/nan/nan.h:672:12: error: no matching function for call to 'New'
    return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
           ^~~~~~~~~~~~~~~~~
/Users/dan/.node-gyp/4.1.0/src/node_buffer.h:31:40: note: candidate function not viable:
      no known conversion from 'uint32_t' (aka 'unsigned int') to 'enum encoding' for 3rd
      argument
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/dan/.node-gyp/4.1.0/src/node_buffer.h:43:40: note: candidate function not viable:
      2nd argument ('const char *') would lose const qualifier
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/dan/.node-gyp/4.1.0/src/node_buffer.h:28:40: note: candidate function not viable:
      requires 2 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                       ^
/Users/dan/.node-gyp/4.1.0/src/node_buffer.h:36:40: note: candidate function not viable:
      requires 5 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
In file included from ../src/bufferutil.cc:16:
../node_modules/nan/nan.h:676:12: error: no viable conversion from
      'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object>'
    return node::Buffer::New(v8::Isolate::GetCurrent(), size);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/dan/.node-gyp/4.1.0/deps/v8/include/v8.h:210:7: note: candidate constructor (the
      implicit copy constructor) not viable: no known conversion from
      'v8::MaybeLocal<v8::Object>' to 'const v8::Local<v8::Object> &' for 1st argument
class Local {
      ^
/Users/dan/.node-gyp/4.1.0/deps/v8/include/v8.h:210:7: note: candidate constructor (the
      implicit move constructor) not viable: no known conversion from
      'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object> &&' for 1st argument
class Local {
      ^
/Users/dan/.node-gyp/4.1.0/deps/v8/include/v8.h:214:13: note: candidate template ignored:
      could not match 'Local' against 'MaybeLocal'
  V8_INLINE Local(Local<S> that)
            ^
/Users/dan/.node-gyp/4.1.0/deps/v8/include/v8.h:326:13: note: candidate template ignored:
      could not match 'S *' against 'v8::MaybeLocal<v8::Object>'
  V8_INLINE Local(S* that)
            ^
In file included from ../src/bufferutil.cc:16:
../node_modules/nan/nan.h:683:26: error: no member named 'Use' in namespace 'node::Buffer'
    return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
           ~~~~~~~~~~~~~~^
In file included from ../src/bufferutil.cc:7:
/Users/dan/.node-gyp/4.1.0/deps/v8/include/v8.h:221:5: error: assigning to
      'v8::Primitive *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/dan/.node-gyp/4.1.0/deps/v8/include/v8.h:180:37: note: expanded from macro
      'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:414:12: note: in instantiation of function template
      specialization 'v8::Local<v8::Primitive>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::Undefined(v8::Isolate::GetCurrent())));
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/bufferutil.cc:7:
/Users/dan/.node-gyp/4.1.0/deps/v8/include/v8.h:221:5: error: assigning to
      'v8::Boolean *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/dan/.node-gyp/4.1.0/deps/v8/include/v8.h:180:37: note: expanded from macro
      'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:424:12: note: in instantiation of function template
      specialization 'v8::Local<v8::Boolean>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::True(v8::Isolate::GetCurrent())));
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/bufferutil.cc:7:
/Users/dan/.node-gyp/4.1.0/deps/v8/include/v8.h:221:5: error: assigning to
      'v8::Function *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/dan/.node-gyp/4.1.0/deps/v8/include/v8.h:180:37: note: expanded from macro
      'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1514:12: note: in instantiation of function template
      specialization 'v8::Local<v8::Function>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(handle)->Get(kCallbackIndex)
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/bufferutil.cc:7:
/Users/dan/.node-gyp/4.1.0/deps/v8/include/v8.h:221:5: error: assigning to
      'v8::Object *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/dan/.node-gyp/4.1.0/deps/v8/include/v8.h:180:37: note: expanded from macro
      'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1632:12: note: in instantiation of function template
      specialization 'v8::Local<v8::Object>::Local<v8::Value>' requested here
    return NanEscapeScope(handle->Get(NanNew(key)).As<v8::Object>());
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
9 errors generated.
make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/amok/node_modules/bufferutil
gyp ERR! node -v v4.1.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "amok"
npm ERR! node v4.1.0
npm ERR! npm  v3.3.3
npm ERR! code ELIFECYCLE

npm ERR! bufferutil@1.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bufferutil@1.1.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bufferutil package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bufferutil
npm ERR! There is likely additional logging output above.
```

This works fine, however (maybe it's the version of bufferutil?):

```
dan@galaxy ~ [1]> npm install -g bufferutil

> bufferutil@1.2.1 install /usr/local/lib/node_modules/bufferutil
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
/usr/local/lib
└─┬ bufferutil@1.2.1
  ├── bindings@1.2.1
  └── nan@2.0.9
```

**Comment by caspervonb** [comment]
Basically everything that depends on native modules broke with node v4.x.
However, despite the error messages it *should* still work, as these are optional dependencies of the `ws` library. It continues the install right?

**Comment by caspervonb** [comment]
Had a quick look at bufferutil's repo, looks like they've recently upgraded NaN https://github.com/websockets/bufferutil/commit/440faef60ee4ddaf163f8248308a4dccaeb76160

**Comment by caspervonb** [comment]
Actually here's the upstream issue https://github.com/websockets/bufferutil/issues/17
And the commit which it landed in `ws` https://github.com/websockets/ws/commit/ee660710e151779a258f29f33040234c3133a63a

So we should upgrade to` ws@0.8`.

For now, any users that run into this these errors are safe to ignore. Optional dependencies.
You can skip them all together with `npm install --no-optional`, but even when they fail it just looks messy but it will still install cleanly.

**Comment by omnidan** [comment]
> It continues the install right? (I've yet to try on Node 4 OS X as I'm having a 'windows' week on low-end gear)

I'm not sure... after running it, the `amok` command is not available.

> You can skip them all together with npm install --no-optional, but even when they fail it just looks messy but it will still install cleanly.

This installed file, but now I have another issue:

```
dan@galaxy ~> amok
env: node\r: No such file or directory
```

**Comment by caspervonb** [comment]
Ah... damn did not think of that. Most likely this is because the latest release (1.1.4) was published from a windows machine with line endings being \n\r.

For now you can roll back to 1.1.3, I'll get a fix out shortly.

```sh
npm install --no-optional --global amok@1.1.3 
```

**Comment by omnidan** [comment]
@caspervonb no worries :sweat_smile:

1.1.3 works fine :tada:

```
dan@galaxy ~> npm install --no-optional --global amok@1.1.3
/usr/local/bin/amok -> /usr/local/lib/node_modules/amok/bin/amok
/usr/local/lib
└── amok@1.1.3

dan@galaxy ~> amok

  Usage: amok [OPTION ...] <URL | FILE>
```

**Comment by caspervonb** [comment]
1.1.4 was unpublished #160

**Comment by caspervonb** [comment]
Master is now tracking node v4/v5, closing this.
