### ISSUE TITLE
Error with blank .js file compilation

### ISSUE THREAD

**Issue by designeng** [caspervonb/amok#163]
When the target .js file is blank (or with commented code inside), `amok --compiler babel index.js` cause to error 
```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
```

**Comment by designeng** [comment]
Sorry, I have this error with any es6 valid code inside. So this command does not work for me.

**Comment by caspervonb** [comment]
That's because there's no target to connect to. Either spawn on with `--browser chrome` or have it open already.

**Comment by caspervonb** [comment]
Ping @designeng, please inform if the issue was resolved with the suggested solution or not :wink:

**Comment by caspervonb** [comment]
Closing this due to inactivity, please feel free to submit additional information or open a new issue if the problem was not resolved.
