### ISSUE TITLE
Getting Amok to run on OSX

### ISSUE THREAD

**Issue by caspervonb** [caspervonb/amok#31]
Hey guys, If anyone running on OSX could do a quick verification that the most basic example actually works that would be great, I'm testing daily on Linux but need to be sure I'm not spreading false information when working on the docs.

```shell
npm install --global amok watchify
cd ~
mkdir amok-demo
cd amok-demo
wget https://gist.githubusercontent.com/caspervonb/d58c3eecb72ba3dd0846/raw/a446dcb93459b14dab4c46561ab14ad03d2a4a10/canvas.js

# 0.9.x
amok canvas.js --bundler 'watchify -o $@' --browser '"/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome" --remote-debugging-port=9222 --user-data-dir=~/amok-chrome' --verbose

# if, 0.10.x (not yet released as I'm writing this)
amok canvas.js --compiler 'watchify -o $@' --client '"/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome" --remote-debugging-port=9222 --user-data-dir=~/amok-chrome' --verbose
```

Then just change the color of the ball or something and save, if it doesn't recompile live in the browser please dump the log.

ping @mattdesl @gaearon @fczuardi 

Cheers

**Comment by karlperemil** [comment]
change wget to:

```
curl https://gist.githubusercontent.com/caspervonb/d58c3eecb72ba3dd0846/raw/a446dcb93459b14dab4c46561ab14ad03d2a4a10/canvas.js > canvas.js
```

Can't get it to work though.

```
Starting server...
Server listening on http://127.0.0.1:9966
Spawning client...

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:998:11)
    at Process.ChildProcess._handle.onexit (child_process.js:789:34)

```

**Comment by scottmessinger** [comment]
I'm really excited by amok! It sounds amazing. To open Chrome, I had to do:
```shell
open -a Google\ Chrome --args -remote-debugging-port=9222
```

and then:
```shell
$ amok canvas.js 

/usr/local/lib/node_modules/amok/node_modules/rdbg/index.js:82
    var socket = ws.connect(target.webSocketDebuggerUrl);
                                  ^
TypeError: Cannot read property 'webSocketDebuggerUrl' of undefined
    at ChromeConnection.attach (/usr/local/lib/node_modules/amok/node_modules/rdbg/index.js:82:35)
    at /usr/local/lib/node_modules/amok/index.js:90:12
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/amok/node_modules/rdbg/index.js:72:9)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)
```

Adding `--bundler  'watchify -o $@'` produced the same output

I hope that helps!

**Comment by mattdesl** [comment]
Currently getting this:

```
npm ERR! notarget No compatible version found: rdbg@'>=0.3.3-0 <0.4.0-0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.0.1","0.0.2","0.1.0","0.2.0","0.2.1","0.3.0","0.3.1","0.3.2"]
```

**Comment by xgrommx** [comment]
I agree with @mattdesl. I got the same result.

**Comment by caspervonb** [comment]
@mattdesl @xgrommx thanks, had forgotten to actually publish 0.3.3. fixed as of right now.

**Comment by caspervonb** [comment]
New instructions tho, since  the interface changed.

```sh
git https://gist.github.com/d58c3eecb72ba3dd0846.git examples
cd examples
amok --client chrome canvas.js
```

**Comment by scottmessinger** [comment]
It worked! Very cool.

**Comment by caspervonb** [comment]
Great, closing this :grinning:

**Comment by malkomalko** [comment]
with 0.13.2

```
> amok --client chrome canvas.js
error client: Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)
```

**Comment by caspervonb** [comment]
@malkomalko what is the path of chrome on your system?
