### ISSUE TITLE
Getting Started Guide

### ISSUE THREAD

**Issue by jdarling** [caspervonb/amok#35]
Would be nice to have a basic getting started guide.

Something along the lines of:

Install amok:
```
sudo npm install -g amok
```

Create your first amok project:
```
mkdir amokproject
```

Create an index.html file with the following contents:
```
<!DOCTYPE html>
<html>
  <body>
    <script type="text/javascript" src="/app.js"></script>
  </body>
</html>
```

Create an app.js with the following contents:
```
document.querySelector('body').innerHTML = 'Hello World!';
```

Start amok:
```
amok --client chrome app.js
```

See the glory!

Edit the code in app.js:
```
document.querySelector('body').innerHTML = 'Hello World 2!';
```

See it update.

Profit!

Unfortunately I don't know if this is correct or not as when I try doing exactly this after installing and configuring to Linux (ElementaryOS Freya) I get the following output:

```
[3770:3770:0402/143452:ERROR:browser_main_loop.cc(198)] GTK theme error: Unable to locate theme engine in module_path: "pixmap",
[3770:3770:0402/143452:ERROR:browser_main_loop.cc(198)] GTK theme error: Unable to locate theme engine in module_path: "pixmap",
[3770:3770:0402/143452:ERROR:browser_main_loop.cc(198)] GTK theme error: Unable to locate theme engine in module_path: "pixmap",
[3770:3770:0402/143452:ERROR:browser_main_loop.cc(198)] GTK theme error: Unable to locate theme engine in module_path: "pixmap",
[3770:3770:0402/143452:ERROR:browser_main_loop.cc(198)] GTK theme error: Unable to locate theme engine in module_path: "pixmap",
Gtk-Message: Failed to load module "canberra-gtk-module"
ATTENTION: default value of option force_s3tc_enable overridden by environment.
Created new window in existing browser session.

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: connect ECONNREFUSED
    at errnoException (net.js:901:11)
    at Object.afterConnect [as oncomplete] (net.js:892:19)
jdarling@elementary-red:~/amokproject$ amok --client chrome app.js
[3873:3873:0402/143504:ERROR:browser_main_loop.cc(198)] GTK theme error: Unable to locate theme engine in module_path: "pixmap",
[3873:3873:0402/143504:ERROR:browser_main_loop.cc(198)] GTK theme error: Unable to locate theme engine in module_path: "pixmap",
[3873:3873:0402/143504:ERROR:browser_main_loop.cc(198)] GTK theme error: Unable to locate theme engine in module_path: "pixmap",
[3873:3873:0402/143504:ERROR:browser_main_loop.cc(198)] GTK theme error: Unable to locate theme engine in module_path: "pixmap",
[3873:3873:0402/143504:ERROR:browser_main_loop.cc(198)] GTK theme error: Unable to locate theme engine in module_path: "pixmap",
Gtk-Message: Failed to load module "canberra-gtk-module"
ATTENTION: default value of option force_s3tc_enable overridden by environment.
[3873:3873:0402/143505:ERROR:extension_downloader.cc(696)] Invalid URL: '' for extension onmkoldigcfmebcinpmineoadckalllb
[3873:3960:0402/143505:ERROR:get_updates_processor.cc(240)] PostClientToServerMessage() failed during GetUpdates

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: connect ECONNREFUSED
    at errnoException (net.js:901:11)
    at Object.afterConnect [as oncomplete] (net.js:892:19)
```

Chrome launches but due to the error I get no live updates :(

**Comment by caspervonb** [comment]
Hang tight for #34, simplifies usage a lot, will be out during the weekend.

```sh
amok --client chrome
```

**Comment by caspervonb** [comment]
/docs will be up on the website eventually, for now there's the readme. If you have any specific questions please feel free to open an issue and they will be answered and rolled into the readme or FAQ, thanks :smile:
