### ISSUE TITLE
Can not execute on windows

### ISSUE THREAD

**Issue by pcjpcj2** [caspervonb/amok#58]
I use windows 7, 
I just installed node, npm and I try to execute amok.

but 

```
C:\>amok --client chrome app.js
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: watch EPERM
    at exports._errnoException (util.js:746:11)
    at FSWatcher.start (fs.js:1172:11)
    at Object.fs.watch (fs.js:1198:11)
    at createFsWatchInstance (C:\Users\user\AppData\Roaming\npm\node_modules\amo
k\node_modules\chokidar\lib\nodefs-handler.js:37:15)
    at setFsWatchListener (C:\Users\user\AppData\Roaming\npm\node_modules\amok\n
ode_modules\chokidar\lib\nodefs-handler.js:77:19)
    at EventEmitter.NodeFsHandler._watchWithNodeFs (C:\Users\user\AppData\Roamin
g\npm\node_modules\amok\node_modules\chokidar\lib\nodefs-handler.js:225:14)
    at EventEmitter.NodeFsHandler._handleFile (C:\Users\user\AppData\Roaming\npm
\node_modules\amok\node_modules\chokidar\lib\nodefs-handler.js:252:21)
    at EventEmitter.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\
amok\node_modules\chokidar\lib\nodefs-handler.js:465:21)
    at FSReqWrap.oncomplete (fs.js:95:15)
```

Amok has not supported Windows 7?

**Comment by caspervonb** [comment]
Hm, looks like you don't have permissions for that folder. Better move into a folder which your user owns.
