### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by goliatone** [caspervonb/amok#59]
Error running npm install

```sh
$ npm install --global amok

npm http GET https://registry.npmjs.org/amok
npm http 200 https://registry.npmjs.org/amok
npm http GET https://registry.npmjs.org/amok/-/amok-0.12.7.tgz
npm http 200 https://registry.npmjs.org/amok/-/amok-0.12.7.tgz
npm http GET https://registry.npmjs.org/chokidar
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/commander
npm http GET https://registry.npmjs.org/mime
npm http GET https://registry.npmjs.org/rdbg
npm http GET https://registry.npmjs.org/temp
npm http GET https://registry.npmjs.org/which
npm http 200 https://registry.npmjs.org/chokidar
npm ERR! Error: No compatible version found: chokidar@'^1.0.0-rc4'
npm ERR! Valid install targets:
npm ERR! ["1.0.0-rc1","1.0.0-rc1.1","1.0.0-rc2","0.1.1","0.2.0","0.2.1","0.2.2","0.2.3","0.2.4","0.2.5","0.2.6","0.3.0","0.4.0","0.5.0","0.5.1","0.5.2","0.5.3","0.6.0","0.6.1","0.6.2","0.6.3","0.7.0","0.7.1","0.8.0","0.8.1","0.8.2","0.8.3","0.8.4","0.9.0","0.10.0","0.10.1","0.10.2","0.10.3","0.10.4","0.10.5","0.10.6","0.10.7","0.10.8","0.10.9","0.11.0","0.11.1","0.12.0","0.12.1","0.12.2","0.12.3","0.12.4","0.12.5","0.12.6","1.0.0-rc1","1.0.0-rc1.1","1.0.0-rc2","1.0.0-rc3","1.0.0-rc4","1.0.0-rc5"]
npm ERR!     at installTargetsError (/Users/goliatone/.nvm/v0.8.23/lib/node_modules/npm/lib/cache.js:685:10)
npm ERR!     at /Users/goliatone/.nvm/v0.8.23/lib/node_modules/npm/lib/cache.js:607:10
npm ERR!     at saved (/Users/goliatone/.nvm/v0.8.23/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:297:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 13.4.0
npm ERR! command "/Users/goliatone/.nvm/v0.8.23/bin/node" "/Users/goliatone/.nvm/v0.8.23/bin/npm" "install" "--global" "amok"
npm ERR! cwd /Users/goliatone/Development/magical-winged-unicorns
npm ERR! node -v v0.8.23
npm ERR! npm -v 1.2.18
npm http 200 https://registry.npmjs.org/rdbg
npm http 200 https://registry.npmjs.org/mime
npm http 200 https://registry.npmjs.org/async
npm http 200 https://registry.npmjs.org/which
npm http 200 https://registry.npmjs.org/temp
npm http 200 https://registry.npmjs.org/commander
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/goliatone/Development/magical-winged-unicorns/npm-debug.log
npm ERR! not ok code 0
```

**Comment by caspervonb** [comment]
Not ssure what to make of this, `^1.0.0-rc4` is a valid version?

**Comment by goliatone** [comment]
Run it again on a different computer, no issues. Will try again tomorrow on the computer that gave me that error.

**Comment by caspervonb** [comment]
The other machine, was running without nvm?

**Comment by goliatone** [comment]
I have `nvm` on both machines. Ran it today and no issues. Not sure what was going on.

**Comment by caspervonb** [comment]
:+1:
