### ISSUE TITLE
Can't use dev tools at the same time

### ISSUE THREAD

**Issue by xgrommx** [caspervonb/amok#69]
Hello @caspervonb. When I open chrome dev tools Amok doesn't work and thrown this error:

```
error debugger: Error: not opened
    at WebSocket.send (C:\Users\dstoyanov\AppData\Roaming\npm\node_modules\amok\node_modules\rdbg\node_modules\ws\lib\WebSocket.js:214:16)
    at ChromeConnection._send (C:\Users\dstoyanov\AppData\Roaming\npm\node_modules\amok\node_modules\rdbg\index.js:45:20)
    at ChromeConnection.evaluate (C:\Users\dstoyanov\AppData\Roaming\npm\node_modules\amok\node_modules\rdbg\index.js:154:10)
    at emit (C:\Users\dstoyanov\AppData\Roaming\npm\node_modules\amok\index.js:174:14)
    at EventEmitter.<anonymous> (C:\Users\dstoyanov\AppData\Roaming\npm\node_modules\amok\index.js:193:7)
    at emitTwo (events.js:92:20)
    at EventEmitter.emit (events.js:169:7)
    at EventEmitter.<anonymous> (C:\Users\dstoyanov\AppData\Roaming\npm\node_modules\amok\node_modules\chokidar\index.js:135:15)
    at EventEmitter.FSWatcher._emit (C:\Users\dstoyanov\AppData\Roaming\npm\node_modules\amok\node_modules\chokidar\index.js:148:5)
    at EventEmitter.<anonymous> (C:\Users\dstoyanov\AppData\Roaming\npm\node_modules\amok\node_modules\chokidar\lib\nodefs-handler.js:263:16)
error debugger: Error: not opened
    at WebSocket.send (C:\Users\dstoyanov\AppData\Roaming\npm\node_modules\amok\node_modules\rdbg\node_modules\ws\lib\WebSocket.js:214:16)
    at ChromeConnection._send (C:\Users\dstoyanov\AppData\Roaming\npm\node_modules\amok\node_modules\rdbg\index.js:45:20)
    at ChromeConnection.evaluate (C:\Users\dstoyanov\AppData\Roaming\npm\node_modules\amok\node_modules\rdbg\index.js:154:10)
    at emit (C:\Users\dstoyanov\AppData\Roaming\npm\node_modules\amok\index.js:174:14)
    at EventEmitter.<anonymous> (C:\Users\dstoyanov\AppData\Roaming\npm\node_modules\amok\index.js:183:7)
    at emitTwo (events.js:92:20)
    at EventEmitter.emit (events.js:169:7)
    at EventEmitter.<anonymous> (C:\Users\dstoyanov\AppData\Roaming\npm\node_modules\amok\node_modules\chokidar\index.js:135:15)
    at EventEmitter.FSWatcher._emit (C:\Users\dstoyanov\AppData\Roaming\npm\node_modules\amok\node_modules\chokidar\index.js:148:5)
    at EventEmitter.NodeFsHandler._handleFile (C:\Users\dstoyanov\AppData\Roaming\npm\node_modules\amok\node_modules\chokidar\lib\nodefs-handler.js:275:10)
error debugger: Error: not opened
    at WebSocket.send (C:\Users\dstoyanov\AppData\Roaming\npm\node_modules\amok\node_modules\rdbg\node_modules\ws\lib\WebSocket.js:214:16)
    at ChromeConnection._send (C:\Users\dstoyanov\AppData\Roaming\npm\node_modules\amok\node_modules\rdbg\index.js:45:20)
    at ChromeConnection.evaluate (C:\Users\dstoyanov\AppData\Roaming\npm\node_modules\amok\node_modules\rdbg\index.js:154:10)
    at emit (C:\Users\dstoyanov\AppData\Roaming\npm\node_modules\amok\index.js:174:14)
    at EventEmitter.<anonymous> (C:\Users\dstoyanov\AppData\Roaming\npm\node_modules\amok\index.js:193:7)
    at emitTwo (events.js:92:20)
    at EventEmitter.emit (events.js:169:7)
    at EventEmitter.<anonymous> (C:\Users\dstoyanov\AppData\Roaming\npm\node_modules\amok\node_modules\chokidar\index.js:135:15)
    at EventEmitter.FSWatcher._emit (C:\Users\dstoyanov\AppData\Roaming\npm\node_modules\amok\node_modules\chokidar\index.js:148:5)
    at EventEmitter.<anonymous> (C:\Users\dstoyanov\AppData\Roaming\npm\node_modules\amok\node_modules\chokidar\lib\nodefs-handler.js:263:16)
```

**Comment by caspervonb** [comment]
You can't have dev tools open at the same time.

**Comment by xgrommx** [comment]
@caspervonb Can I use chrome console?

**Comment by barneycarroll** [comment]
This is a bit of a pain. I understand the fact that you can't push hot code into an inspected environment, and opening and closing the inspector between debugging and writing code isn't so bad (although in the far future I'd really like to see this squashed). The problem for me is debugging initialisation code. Could we pass a flag to Amok to have the dev tools open with 'pause on error' on init?

**Comment by caspervonb** [comment]
> Can I use chrome console?
@xgrommx chrome console and chrome inspector are referring to the same thing?

> This is a bit of a pain. I understand the fact that you can't push hot code into an inspected environment, and opening and closing the inspector between debugging and writing code isn't so bad (although in the far future I'd really like to see this squashed). The problem for me is debugging initialisation code. Could we pass a flag to Amok to have the dev tools open with 'pause on error' on init?
@barneycarroll Possible, but preferably not before the rest of amok has breakpoints in general (socket protocol, repl), wouldn't a debugger statement break tho?

**Comment by barneycarroll** [comment]
wouldn't a debugger statement break tho?

@caspervonb no idea – TBH I don't really understand how splitting the execution environment works in the first place ;)

**Comment by xgrommx** [comment]
@caspervonb I would like use chrome javascript console with amok.

**Comment by caspervonb** [comment]
Go star [crbug.com/129539](http://crbug.com/129539) on the chrome tracker ;)

**Comment by caspervonb** [comment]
A few options here with varying mileage.

1. Wait until a fix lands in chrome, the issue has around 1k stars, but it is also rather old (@paul_irish, any ideas if this will ever land?)
2. Implement a multiplexer that sits in-between amok and chrome that allows additional chrome protocol sockets to connect. This still will not let  you open a tab however, but it will let you open external dev tools.
3. Untested theory, chrome.debugger (extension) namespace might be allowed to live along side embedded dev tools.

**Comment by caspervonb** [comment]
Extension is a no-go, dev tools inspector still takes priority over the debugger connection.

**Comment by caspervonb** [comment]
So, I will be implementing a multiplexer **soon**, primarily to enable existing this party tools to connect through amok, elevating the need for #25.

But the actual issue that chrome kills all connections when you open the inspector is something that has to be solved internally in chrome.

Closing this issue as it is documented in the manual now, and it can't be fixed.
